sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  global:
    - TSADM_LOG=OFF

install:
  - pip install Django>=1.9,<=1.10

script:
  - python manage.py test

notifications:
  irc:
    - irc.freenode.org#tsadm
