DOCKER_IMG ?= tsadm/master
DOCKER_DEVIMG ?= tsadm/masterdev
DOCKER_MASTER_NAME ?= tsadm-master
DOCKER_CMD ?=
DOCKER_ARGS ?=
DOCKER_UID ?= $(shell id -u)
DOCKER_GID ?= $(shell id -g)
DOCKER_UMASK ?= $(shell umask)
TEST_SUITE ?=
TSADM_LOG ?= off
