# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsadmhost', '0001_initial'),
        ('tsadmsite', '0002_auto_20160203_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSAdmSiteEnvDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsadmhost.TSAdmHostDB')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsadmsite.TSAdmSiteDB')),
            ],
            options={
                'verbose_name_plural': 'SiteEnvs',
                'verbose_name': 'SiteEnv',
            },
        ),
    ]
