# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsadmuser', '0002_auto_20160203_2058'),
        ('tsadmsite', '0003_tsadmsiteenvdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSAdmSiteEnvACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteenv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsadmsite.TSAdmSiteEnvDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsadmuser.TSAdmUserDB')),
            ],
            options={
                'verbose_name': 'SiteEnvACL',
                'verbose_name_plural': 'SiteEnvsACL',
            },
        ),
        migrations.AddField(
            model_name='tsadmsiteenvdb',
            name='users',
            field=models.ManyToManyField(related_name='siteenv', through='tsadmsite.TSAdmSiteEnvACL', to='tsadmuser.TSAdmUserDB'),
        ),
    ]
