# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSAdmHostDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Hosts',
                'verbose_name': 'Host',
            },
        ),
    ]
