DOCKER_IMG ?= tsadm/masterdev

include ../mk/env.mk

.PHONY: apidoc
apidoc:
	rm -rf src
	sphinx-apidoc -e -o src/ ../src/


.PHONY: run-sphinx
run-sphinx:
	docker run -it --rm --user $(shell id -u):$(shell id -g) \
		-v $(PWD)/..:/opt/tsadm/webapp \
		-w /opt/tsadm/webapp/docs \
		$(DOCKER_IMG) make html
